In [2]:
import pandas as pd
import numpy as np
import pickle

In [39]:
df_csv= pd.read_pickle("../df_noplus/df5.pkl")

In [40]:
all_subjects=df_csv['COURSEID'].value_counts()
##removing any subject enrolled less than 20 times
m20=all_subjects[all_subjects[:]>=20]
print df_csv.shape
df_csv=df_csv[df_csv["COURSEID"].isin(m20.index)]
print df_csv.shape

(28272, 199)
(27994, 199)


In [41]:
df=df_csv[df_csv['COURSEID']=='CS213']
#df["COURSEID"].value_counts()
#df=pd.read_csv('../df_m20/df_CS213.csv',index_col=0)
df=df.iloc[np.random.permutation(len(df))]

In [42]:
x_head=df.columns[4:]
y_head=['GRADE']
print x_head
print y_head
x=df.as_matrix(x_head)
y=df.as_matrix(y_head).T[0]

Index([u'AN201', u'AS171', u'AS177', u'AS178', u'AT207', u'AT316', u'AT326',
       u'AT336', u'AT346', u'AT366',
       ...
       u'TU110', u'TU111', u'TU115', u'TU116', u'TU120', u'TU122', u'TU130',
       u'TU153', u'TU154', u'TU156'],
      dtype='object', length=195)
['GRADE']


In [7]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn import svm
from sklearn.cross_validation import cross_val_score

clf_dt = DecisionTreeClassifier(max_depth=None, 
    min_samples_split=1, random_state=None, max_features=None)
scores = cross_val_score(clf_dt, x, y, cv=5)
print scores
print "--Decision Tree: %s"%scores.mean()

clf_rf=RandomForestClassifier(n_estimators=10, max_depth=None, 
    min_samples_split=1, random_state=None, max_features=None)
scores = cross_val_score(clf_rf, x, y, cv=5)
print scores
print "--Random Forest: %s"%scores.mean()

clf_et = ExtraTreesClassifier(n_estimators=10, max_depth=None, 
    min_samples_split=1, random_state=None, max_features=None)
scores = cross_val_score(clf_et, x, y, cv=5)
print scores
print "--Extra Tree: %s"%scores.mean()

clf_svm = svm.SVC()
scores = cross_val_score(clf_svm, x, y, cv=5)
print scores
print "--SVM: %s"%scores.mean()

[ 0.47741935  0.36363636  0.40131579  0.44078947  0.48026316]
--Decision Tree: 0.432684827906
[ 0.49032258  0.48701299  0.5         0.50657895  0.45394737]
--Random Forest: 0.48757237669
[ 0.43225806  0.48051948  0.46052632  0.5         0.48026316]
--Extra Tree: 0.470713403744
[ 0.45806452  0.46103896  0.46710526  0.51973684  0.51315789]
--SVM: 0.483820695434


In [54]:
clf_et.fit(x[10:],y[10:])

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features=None, max_leaf_nodes=None,
           min_samples_leaf=1, min_samples_split=1,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [71]:
clf_et.apply(x[:20])

array([[475, 465, 585, 486, 512, 592, 385, 335, 555, 568],
       [ 96,  43, 122, 166, 145,  99,  14, 137, 236,  98],
       [333, 343, 356, 341, 245, 423, 323, 285, 490, 454],
       [241, 249, 207, 275,  66, 246, 218, 257, 356, 297],
       [404, 315, 408, 388, 437, 356, 540, 443, 441, 400],
       [404, 425, 416, 403, 384, 363, 494, 418, 439, 522],
       [392, 306, 379, 401, 397, 461, 494, 416, 528, 498],
       [245, 211, 203,  10,  24, 222, 206, 234,  82, 287],
       [243, 233, 207,  17, 262, 343, 209, 241, 103, 311],
       [ 42, 156, 160,  28, 174,  84,  80,  33,  78,  74],
       [600, 579, 509, 605, 645, 516, 624, 603, 621, 255],
       [127, 102, 167, 176, 159, 128, 144, 128, 249, 114],
       [128, 177, 195, 158,  46, 117, 190, 167, 248, 101],
       [287, 317, 283, 280, 228, 285, 258, 284, 383, 361],
       [ 74,  25,  73, 120,  72,  10,  39,  46,  29,  34],
       [212, 195, 179, 236, 397, 205, 184, 414, 313, 188],
       [294, 242, 248,  99, 229, 279, 259, 281,  96, 359

In [72]:
np.bincount(clf_et.predict(x)).shape

(9L,)

In [80]:
clf_et.predict(x[1])

array([5], dtype=int64)

In [84]:
np.max(clf_et.predict_proba(x[1]))

0.90000000000000002

In [28]:
clf_et.predict_proba(x[0,:])

array([[ 0.,  0.,  0.,  1.,  0.,  0.]])

In [29]:
clf_et.predict_log_proba(x[0,:])

array([[-inf, -inf, -inf,   0., -inf, -inf]])