In [1]:
pwd

u'C:\\Users\\Wasit\\Google Drive\\Somkiat\\data_csgrade_wasit\\wasit\\_pforest'

In [2]:
import os
sname='CS213' #subject_name
if not os.path.exists(sname):
    os.makedirs(sname)

In [3]:
import pandas as pd

df= pd.read_pickle("../df_m20/df5.pkl")
df=df[df['COURSEID']==sname]
#df["COURSEID"].value_counts()
#df=pd.read_csv('../df_m20/df_CS213.csv',index_col=0)
df

C:\Anaconda\lib\site-packages\pandas\computation\__init__.py:19: UserWarning: The installed version of numexpr 2.4.4 is not supported in pandas and will be not be used

  UserWarning)


STUDENTID COURSEID  GRADE   TERM  AN201  AS171  AS177  AS178  AT207  \
16        316644    CS213      9  25531      0      0      0      0      0   
123       321848    CS213     10  25531      0      0      0      0      0   
171       321849    CS213      8  25531      0      0      0      0      0   
193       321849    CS213     10  25542      0      0      0      0      0   
225       321850    CS213      9  25531      0      0      0      0      0   
275       324840    CS213      5  25531      0      0      0      0      0   
283       324840    CS213      7  25532      0      0      0      0      0   
295       324840    CS213      9  25542      0      0      0      0      0   
337       324842    CS213      6  25531      0      0      0      0      0   
354       324842    CS213      6  25542      0      0      0      0      0   
395       329171    CS213      8  25531      0      0      0      0      0   
415       329171    CS213     11  25542      0      0      0      0      0   
445       329172    CS213      7  25531      0      0      0      0      0   
468       329172    CS213     11  25542      0      0      0      0      0   
498       329173    CS213      9  25531      0      0      0      0      0   
547       329174    CS213      8  25531      0      0      0      0      0   
568       329174    CS213     12  25542      0      0      0      0      0   
599       329175    CS213      9  25531      0      0      0      0      0   
651       329176    CS213      6  25531      0      0      0      0      0   
670       329176    CS213     11  25542      0      0      0      0      0   
702       329177    CS213      9  25531      0      0      0      0      0   
765       329179    CS213      5  25531      0      0      0      0      0   
786       329180    CS213      8  25531      0      0      0      0      0   
806       329180    CS213     11  25542      0      0      0      0      0   
837       329181    CS213     13  25531      0      0      0      0      0   
883       329182    CS213     11  25531      0      0      0      0      0   
933       329183    CS213      7  25531      0      0      0      0      0   
954       329183    CS213     12  25542      0      0      0      0      0   
984       329184    CS213      7  25531      0      0      0      0      0   
1006      329184    CS213     12  25542      0      0      0      0      0   
...          ...      ...    ...    ...    ...    ...    ...    ...    ...   
27852     427169    CS213      6  25571      0      0      0      0      0   
27933     427173    CS213     11  25571      0      0      0      0      0   
27965     427174    CS213      6  25571      0      0      0      0      0   
28011     427177    CS213      6  25571      0      0      0      0      0   
28044     427178    CS213      6  25571      0      0      0      0      0   
28074     427179    CS213      5  25571      0      0      0      0      0   
28105     427180    CS213      7  25571      0      0      0      0      0   
28152     427183    CS213      6  25571      0      0      0      0      0   
28183     427185    CS213      8  25571      0      0      0      0      0   
28246     427189    CS213      6  25571      0      0      0      0      0   
28281     427190    CS213      6  25571      0      0      0      0      0   
28313     427191    CS213      6  25571      0      0      0      0      0   
28369     427195    CS213      6  25571      0      0      0      0      0   
28402     427196    CS213      6  25571      0      0      0      0      0   
28433     427197    CS213      5  25571      0      0      0      0      0   
28459     427198    CS213      6  25571      0      0      0      0      0   
28491     427199    CS213      8  25571      0      0      0      0      0   
28535     427201    CS213      6  25571      0      0      0      0      0   
28610     427204    CS213      6  25571      0      0      0      0      0   
28657     427206    CS213    

In [4]:
x_head=df.columns[3:]
y_head=['GRADE']
print x_head
print y_head
x=df.as_matrix(x_head)
y=df.as_matrix(y_head).T[0]

Index([u'TERM', u'AN201', u'AS171', u'AS177', u'AS178', u'AT207', u'AT316',
       u'AT326', u'AT336', u'AT346',
       ...
       u'TU110', u'TU111', u'TU115', u'TU116', u'TU120', u'TU122', u'TU130',
       u'TU153', u'TU154', u'TU156'],
      dtype='object', length=196)
['GRADE']


In [5]:
import pickle
from sklearn.cross_validation import StratifiedKFold
sfk=StratifiedKFold(y, n_folds=5, shuffle=True)
for i,(train_index, test_index) in enumerate(sfk):
    print "i:%s, train_index:%s, test_index:%s"%(i,train_index,test_index)
    #dataset00.pic
    with open(sname+'/dataset%02d.pic'%(i), 'wb') as pickleFile:
        theta_dim=1
        I=x[test_index]
        L=y[test_index]
        ###please check Clmax
        clmax=14
        theta_range=I.shape[1]
        pickle.dump((clmax,theta_dim,theta_range,len(L),L,I,None), pickleFile, pickle.HIGHEST_PROTOCOL)

i:0, train_index:[  0   1   3   4   5   7   9  11  13  14  15  16  17  18  19  20  21  22
  23  25  26  27  28  29  30  31  32  33  34  36  37  38  40  41  42  43
  46  48  49  51  52  53  54  55  56  57  58  59  60  61  63  66  67  70
  71  72  78  79  80  81  83  84  86  87  89  90  91  92  93  94  95  96
  97  98  99 100 101 102 103 105 106 107 109 110 111 112 114 115 116 117
 118 119 120 121 124 125 126 127 128 129 130 131 132 133 134 135 136 138
 140 141 143 144 145 146 147 148 149 151 152 154 155 156 157 159 160 161
 162 164 165 166 167 169 170 171 172 173 174 175 176 178 179 180 182 183
 184 185 186 188 190 191 193 195 196 197 198 199 200 203 204 205 207 208
 209 210 211 213 214 215 216 217 218 220 221 222 223 224 227 228 229 230
 231 232 233 234 236 237 238 239 241 242 244 245 246 250 251 252 254 255
 256 257 259 260 262 264 265 266 267 268 271 272 273 274 275 276 277 278
 279 281 282 283 284 285 286 287 288 289 290 291 292 293 295 296 297 298
 299 300 302 304 305 306 307 308 3

In [6]:
from pforest.master import master
m=master(dsetname=sname)
m.reset()
m.train()
with open('%s/out_tree1.pic'%(sname), 'wb') as pickleFile:
    pickle.dump(m.root, pickleFile, pickle.HIGHEST_PROTOCOL)

master>>init() dsetname: CS213
master>> create dview
master>> init engine
Found pforest
debug:master:__init__: ['CS213/dataset00.pic', 'CS213/dataset01.pic', 'CS213/dataset02.pic', 'CS213/dataset03.pic']
master>> init local variables
master>>reset()
master>>reset() H: 2.9565
master>>reset() Q: 00615
master::train() node20*-
master::train() node19R-
master::train() node18R-
master::train() node17RG
master::train() node17LG
master::train() node18L-
master::train() node17R-
master::train() node16RG
master::train() node16LG
master::train() node17L-
master::train() node16R-
master::train() node15R-
master::train() node14RQ
master::train() node14LG
master::train() node15L-
master::train() node14RG
master::train() node14LQ
master::train() node16L-
master::train() node15RG
master::train() node15L-
master::train() node14R-
master::train() node13RG
master::train() node13LG
master::train() node14L-
master::train() node13RQ
master::train() node13LG
master::train() node19L-
master::train() node18R-

In [7]:
with open(sname+'/dataset%02d.pic'%(4), 'rb') as pickleFile:
    d=pickle.load(pickleFile)
L=d[4]
I=d[5]

In [8]:
import numpy as np
from pforest.tree import tree
actual=np.array(L)
predict=np.zeros(len(L))
t=tree()
t.settree(m.root)
for i in xrange(len(L)):
    Prob=t.classify(I[i])
    predict[i]=np.argmax(Prob)
   
    print "actual grade:%d predicted grade:%d"%(actual[i],predict[i])

Found pforest
actual grade:9 predicted grade:8
actual grade:9 predicted grade:8
actual grade:11 predicted grade:9
actual grade:8 predicted grade:9
actual grade:6 predicted grade:9
actual grade:12 predicted grade:12
actual grade:12 predicted grade:11
actual grade:8 predicted grade:9
actual grade:9 predicted grade:10
actual grade:7 predicted grade:7
actual grade:13 predicted grade:12
actual grade:13 predicted grade:7
actual grade:9 predicted grade:9
actual grade:9 predicted grade:9
actual grade:11 predicted grade:7
actual grade:9 predicted grade:9
actual grade:10 predicted grade:9
actual grade:7 predicted grade:6
actual grade:8 predicted grade:9
actual grade:7 predicted grade:9
actual grade:8 predicted grade:7
actual grade:9 predicted grade:8
actual grade:5 predicted grade:7
actual grade:7 predicted grade:8
actual grade:11 predicted grade:8
actual grade:9 predicted grade:9
actual grade:9 predicted grade:7
actual grade:11 predicted grade:9
actual grade:10 predicted grade:10
actual grade:9

In [9]:
cm = np.zeros((clmax,clmax))
for i in xrange(len(L)):
    cm[predict[i],actual[i]] +=1
print cm

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   1.   2.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   3.  13.   8.   6.   1.   4.   0.   0.   1.]
 [  0.   0.   0.   0.   0.   1.   1.   2.   2.   3.   0.   2.   0.   1.]
 [  0.   0.   0.   0.   0.   1.   1.   3.   5.  10.   3.   3.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   3.   2.   9.  17.   6.   3.   0.   1.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   5.   6.   1.   1.   3.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   2.   0.   1.   1.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   1.   3.   1.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   1.   0.

In [10]:
tp=0
for i in xrange(clmax):
    tp += cm[i,i]
print tp/cm.sum().sum()

0.333333333333


In [11]:
def fold_index(k=5,N=10):
    x=np.random.permutation(np.arange(N))
    return np.split(x, [(i)*N/k for i in xrange(1,k)])
fold_index(5,765)

[array([437, 692, 436,  95, 106, 676, 202, 365, 418, 751, 136, 286, 316,
        444, 152, 153, 481, 201, 336, 154, 490, 633, 198,  25, 476, 449,
        466, 529, 455, 650, 312, 516, 491,  58, 275, 506, 298, 309, 731,
        595, 272, 540, 324, 507, 103, 685, 100, 393, 489, 108, 511, 125,
        262, 409, 413, 624, 398, 460,  82, 495, 425, 701, 483, 257, 373,
        665, 239, 253, 736, 231,  73, 487, 357, 498, 430, 576, 428, 417,
        387, 359, 504, 644,  38, 705, 613, 350, 266,  91, 494, 343, 424,
        307, 604, 503, 138, 351, 565, 304, 273, 147, 734,  56, 539, 366,
        255, 599,  17, 514, 480, 741, 621, 446, 361, 360, 632, 177, 655,
        362, 513, 342, 645, 310, 335, 630,  90,  94, 637, 246, 719, 207,
        634, 157, 671, 642, 370, 372, 229, 122, 659, 543, 587,  47, 166,
        333, 219, 280,  35, 151, 603, 403, 536, 687, 759]),
 array([353, 581, 562,  92, 669, 713, 739, 702, 326, 620, 414, 756, 278,
        129, 101, 742, 612, 470, 193, 176, 726, 210, 438, 344, 2

In [12]:
import pickle
from pforest.master import master
import numpy as np
from pforest.tree import tree

n_folds=5
N=len(y)
clmax=14
theta_dim=1
sfk=fold_index(k=n_folds,N=N)
recall=np.zeros(n_folds)
for k in xrange(n_folds):
    #prepare the dataset for every core and evaluation
    for j in xrange(n_folds):
        ix=(k+j)%5
        sample_index=sfk[ix]
        with open(sname+'/dataset%02d.pic'%(ix), 'wb') as pickleFile:
            I=x[sample_index]
            L=y[sample_index]
            theta_range=I.shape[1]
            pickle.dump((clmax,theta_dim,theta_range,len(L),L,I,None), pickleFile, pickle.HIGHEST_PROTOCOL)
            
    #train
    m=master(dsetname=sname)
    m.reset()
    m.train()
    with open(sname+'/out_tree%02d.pic'%(k), 'wb') as pickleFile:
        pickle.dump(m.root, pickleFile, pickle.HIGHEST_PROTOCOL)
            
    #load last dataset
    with open(sname+'/dataset%02d.pic'%(n_folds-1), 'rb') as pickleFile:
        d=pickle.load(pickleFile)
        L_last=d[4]
        I_last=d[5]
    ##evaluate    
    actual=np.array(L_last)
    predict=np.zeros(len(L_last))
    t=tree()
    t.settree(m.root)
    for i in xrange(len(L_last)):
        Prob=t.classify(I_last[i])
        predict[i]=np.argmax(Prob)

        #print "actual grade:%d predicted grade:%d"%(actual[i],predict[i])
    ##confustion matrix
    cm = np.zeros((clmax,clmax))
    for i in xrange(len(L)):
        cm[predict[i],actual[i]] +=1
    print cm
    tp=0
    for i in xrange(clmax):
        tp += cm[i,i]
    recall[k]=tp/cm.sum().sum()
    print "fold: %d, recall:%.3f"%(k, recall[k])

master>>init() dsetname: CS213
master>> create dview
master>> init engine
Found pforest
debug:master:__init__: ['CS213/dataset00.pic', 'CS213/dataset01.pic', 'CS213/dataset02.pic', 'CS213/dataset03.pic']
master>> init local variables
master>>reset()
master>>reset() H: 2.9271
master>>reset() Q: 00612
master::train() node20*-
master::train() node19R-
master::train() node18R-
master::train() node17R-
master::train() node16R-
master::train() node15RG
master::train() node15LG
master::train() node16L-
master::train() node15RG
master::train() node15L-
master::train() node14R-
master::train() node13RG
master::train() node13LQ
master::train() node14LG
master::train() node17LG
master::train() node18L-
master::train() node17R-
master::train() node16R-
master::train() node15RG
master::train() node15LG
master::train() node16LG
master::train() node17LG
master::train() node19L-
master::train() node18R-
master::train() node17R-
master::train() node16RG
master::train() node16L-
master::train() node15R-

RuntimeError: Can't purge outstanding tasks: set(['d6b76819-1df8-4b8b-b04e-8f10d0ed9a8b'])

In [ ]:
recall

In [ ]:
recall.mean()

In [ ]:
index