In [1]:
pwd

u'C:\\Users\\Wasit\\Google Drive\\Somkiat\\data_csgrade_wasit\\wasit\\_pforest'

In [2]:
import os
sname='CS213' #subject_name
if not os.path.exists(sname):
    os.makedirs(sname)

In [3]:
import pandas as pd

df= pd.read_pickle("../df_m20/df5.pkl")
df=df[df['COURSEID']==sname]
#df["COURSEID"].value_counts()
#df=pd.read_csv('../df_m20/df_CS213.csv',index_col=0)
df

C:\Anaconda\lib\site-packages\pandas\computation\__init__.py:19: UserWarning: The installed version of numexpr 2.4.4 is not supported in pandas and will be not be used

  UserWarning)


STUDENTID COURSEID  GRADE   TERM  AN201  AS171  AS177  AS178  AT207  \
16        316644    CS213      9  25531      0      0      0      0      0   
123       321848    CS213     10  25531      0      0      0      0      0   
171       321849    CS213      8  25531      0      0      0      0      0   
193       321849    CS213     10  25542      0      0      0      0      0   
225       321850    CS213      9  25531      0      0      0      0      0   
275       324840    CS213      5  25531      0      0      0      0      0   
283       324840    CS213      7  25532      0      0      0      0      0   
295       324840    CS213      9  25542      0      0      0      0      0   
337       324842    CS213      6  25531      0      0      0      0      0   
354       324842    CS213      6  25542      0      0      0      0      0   
395       329171    CS213      8  25531      0      0      0      0      0   
415       329171    CS213     11  25542      0      0      0      0      0   
445       329172    CS213      7  25531      0      0      0      0      0   
468       329172    CS213     11  25542      0      0      0      0      0   
498       329173    CS213      9  25531      0      0      0      0      0   
547       329174    CS213      8  25531      0      0      0      0      0   
568       329174    CS213     12  25542      0      0      0      0      0   
599       329175    CS213      9  25531      0      0      0      0      0   
651       329176    CS213      6  25531      0      0      0      0      0   
670       329176    CS213     11  25542      0      0      0      0      0   
702       329177    CS213      9  25531      0      0      0      0      0   
765       329179    CS213      5  25531      0      0      0      0      0   
786       329180    CS213      8  25531      0      0      0      0      0   
806       329180    CS213     11  25542      0      0      0      0      0   
837       329181    CS213     13  25531      0      0      0      0      0   
883       329182    CS213     11  25531      0      0      0      0      0   
933       329183    CS213      7  25531      0      0      0      0      0   
954       329183    CS213     12  25542      0      0      0      0      0   
984       329184    CS213      7  25531      0      0      0      0      0   
1006      329184    CS213     12  25542      0      0      0      0      0   
...          ...      ...    ...    ...    ...    ...    ...    ...    ...   
27852     427169    CS213      6  25571      0      0      0      0      0   
27933     427173    CS213     11  25571      0      0      0      0      0   
27965     427174    CS213      6  25571      0      0      0      0      0   
28011     427177    CS213      6  25571      0      0      0      0      0   
28044     427178    CS213      6  25571      0      0      0      0      0   
28074     427179    CS213      5  25571      0      0      0      0      0   
28105     427180    CS213      7  25571      0      0      0      0      0   
28152     427183    CS213      6  25571      0      0      0      0      0   
28183     427185    CS213      8  25571      0      0      0      0      0   
28246     427189    CS213      6  25571      0      0      0      0      0   
28281     427190    CS213      6  25571      0      0      0      0      0   
28313     427191    CS213      6  25571      0      0      0      0      0   
28369     427195    CS213      6  25571      0      0      0      0      0   
28402     427196    CS213      6  25571      0      0      0      0      0   
28433     427197    CS213      5  25571      0      0      0      0      0   
28459     427198    CS213      6  25571      0      0      0      0      0   
28491     427199    CS213      8  25571      0      0      0      0      0   
28535     427201    CS213      6  25571      0      0      0      0      0   
28610     427204    CS213      6  25571      0      0      0      0      0   
28657     427206    CS213    

In [4]:
x_head=df.columns[4:]
y_head=['GRADE']
print x_head
print y_head
x=df.as_matrix(x_head)
y=df.as_matrix(y_head).T[0]

Index([u'AN201', u'AS171', u'AS177', u'AS178', u'AT207', u'AT316', u'AT326',
       u'AT336', u'AT346', u'AT366',
       ...
       u'TU110', u'TU111', u'TU115', u'TU116', u'TU120', u'TU122', u'TU130',
       u'TU153', u'TU154', u'TU156'],
      dtype='object', length=195)
['GRADE']


In [5]:
import numpy as np
def fold_index(k=5,N=10):
    x=np.random.permutation(np.arange(N))
    return np.split(x, [(i)*N/k for i in xrange(1,k)])
fold_index(3,23)

[array([19, 10, 12, 18, 13,  5, 11]),
 array([ 1,  3,  6, 20,  8,  0, 14,  7]),
 array([ 2,  4, 21, 22, 17,  9, 16, 15])]

In [6]:
import pickle
from pforest.master import master
import numpy as np
from pforest.tree import tree

n_folds=5
N=len(y)
clmax=14
theta_dim=1
sfk=fold_index(k=n_folds,N=N)
recall=np.zeros(n_folds)
for k in xrange(n_folds):
    #prepare the dataset for every core and evaluation
    for j in xrange(n_folds):
        ix=(k+j)%5
        sample_index=sfk[ix]
        with open(sname+'/dataset%02d.pic'%(ix), 'wb') as pickleFile:
            I=x[sample_index]
            L=y[sample_index]
            theta_range=I.shape[1]
            pickle.dump((clmax,theta_dim,theta_range,len(L),L,I,None), pickleFile, pickle.HIGHEST_PROTOCOL)
            
    #train
    m=master(dsetname=sname)
    m.reset()
    m.train()
    with open(sname+'/out_tree%02d.pic'%(k), 'wb') as pickleFile:
        pickle.dump(m.root, pickleFile, pickle.HIGHEST_PROTOCOL)
            
    #load last dataset
    with open(sname+'/dataset%02d.pic'%(n_folds-1), 'rb') as pickleFile:
        d=pickle.load(pickleFile)
        L_last=d[4]
        I_last=d[5]
    ##evaluate    
    actual=np.array(L_last)
    predict=np.zeros(len(L_last))
    t=tree()
    t.settree(m.root)
    for i in xrange(len(L_last)):
        Prob=t.classify(I_last[i])
        predict[i]=np.argmax(Prob)

        #print "actual grade:%d predicted grade:%d"%(actual[i],predict[i])
    ##confustion matrix
    cm = np.zeros((clmax,clmax))
    for i in xrange(len(L)):
        cm[predict[i],actual[i]] +=1
    print cm
    tp=0
    for i in xrange(clmax):
        tp += cm[i,i]
    recall[k]=tp/cm.sum().sum()
    print "fold: %d, recall:%.3f"%(k, recall[k])

Found pforest
master>>init() dsetname: CS213
master>> create dview
master>> init engine
Found pforest
debug:master:__init__: ['CS213/dataset00.pic', 'CS213/dataset01.pic', 'CS213/dataset02.pic', 'CS213/dataset03.pic']
master>> init local variables
master>>reset()
master>>reset() H: 2.9374
master>>reset() Q: 00612
master::train() node20*-
master::train() node19R-
master::train() node18R-
master::train() node17R-
master::train() node16RG
master::train() node16L-
master::train() node15R-
master::train() node14R-
master::train() node13R-
master::train() node12R-
master::train() node11RG
master::train() node11LG
master::train() node12L-
master::train() node11RG
master::train() node11LQ
master::train() node13L-
master::train() node12RQ
master::train() node12L-
master::train() node11R-
master::train() node10RQ
master::train() node10LG
master::train() node11LG
master::train() node14L-
master::train() node13RG
master::train() node13L-
master::train() node12RG
master::train() node12LG
master::tr

In [7]:
recall

array([ 0.2875817 ,  0.30065359,  0.39869281,  0.31372549,  0.38562092])

In [8]:
recall.mean()

0.33725490196078428